### PR TITLE
Feature: easier installation

### PR DESCRIPTION
**Pull request by behackl**
distribution as a npm package: add `package.json`, add custom script for installing extension, rewrite readme.

### CODE REVIEW

**Comment by dkrenn** [comment]
Wouldn't `install-nbcelltesting` or `jupyter-nbextension-install` be a better name for the `npm` script that `install-nbextension`?

**Comment by dkrenn** [comment]
It should be made clear, that the `$PYFLAG`s are not handled by us, but by `jupyter-nbextension` (and that details can be found there)

**Comment by behackl** [comment]
I also like `install-nbcelltesting` better; feel free to change!

and regarding the second comment: do you have some wording in mind?

**Review by dkrenn — APPROVED** [review]
LGTM, thank you for your effort and changes

**Pull request merged**
